service: ${self:custom.subsys}-bff-service

provider:
  name: aws
  deploymentBucket: ${file(cvo/cfn.yml):deploymentBucket}
  iam:
    deploymentRole: ${file(cvo/cfn.yml):deploymentRole}
    role: ${file(cvo/iam.yml):role}
  stackTags: ${file(cvo/tags.yml)}
  runtime: nodejs20.x
  logRetentionInDays: ${param:logRetentionInDays}
  environment: ${file(cvo/config.yml):environment}
  endpointType: REGIONAL
  # apiGateway: ${file(cvo/apig.yml):apiGateway}

params: ${file(cvo/config.yml):params}
custom: ${file(cvo/config.yml):custom}
package:
  individually: true

plugins:
  - serverless-aws-describe-plugin
  # - serverless-kinesis-esm-plugin
  # - serverless-secrets-mgr-plugin
  - '@convivio/serverless-plugin'

functions:
  rest:
    handler: src/rest/index.handle
    events:
      - http:
          path: '{proxy+}'
          method: any # get
          cors: ${file(cvo/apig.yml):cors}
          authorizer: ${file(cvo/apig.yml):authorizer}
      # - http:
      #     path: '{proxy+}'
      #     method: [put,delete] ????
      #     cors: ${file(cvo/apig.yml):cors}
      #     authorizer: ${file(cvo/apig.yml):authorizer}
  listener:
    handler: src/listener/index.handle
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ ListenerQueue, Arn ]
    #       functionResponseType: ReportBatchItemFailures
    #   - stream:
    #       type: kinesis
    #       arn: ${self:provider.environment.STREAM_ARN}
    #       batchSize: 100
    #       startingPosition: TRIM_HORIZON
    #       filterPatterns:
    #         - data:
    #             type:
    #                - prefix: 'thing-'
  trigger:
    handler: src/trigger/index.handle
    events:
      - stream:
          type: dynamodb
          arn: ${self:custom.tableStreamArn}
          batchSize: 100
          startingPosition: TRIM_HORIZON
          filterPatterns: ${file(cvo/dynamodb.yml):filterPatterns}
      # - sqs:
      #     arn:
      #       Fn::GetAtt: [ TriggerQueue, Arn ]

resources:
  - ${file(cvo/apig.yml):resources}
  - ${file(cvo/sqs-listener.yml):resources}
  - ${file(cvo/dynamodb.yml):resources}
  # - ${file(cvo/s3.yml):resources}
  # - ${file(cvo/sns.yml):resources}
  # - ${file(cvo/sqs-trigger.yml):resources}
  # - ${file(cvo/secrets.yml):resources}
  - ${file(cvo/conditions.yml)}
